# Generated by Django 5.2.3 on 2025-09-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("questions", "0002_question_api_resource_id_question_assembly_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Debate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debate_id", models.CharField(max_length=50, unique=True)),
                ("debate_date", models.DateField()),
                (
                    "debate_type",
                    models.CharField(
                        choices=[
                            ("text_of_debate", "Text of Debate"),
                            ("synopsis", "Synopsis of Debate"),
                            ("uncorrected", "Uncorrected Debate"),
                            ("corrected", "Corrected Debate"),
                        ],
                        default="text_of_debate",
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=50)),
                ("pdf_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Download"),
                            ("downloading", "Downloading"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("not_available", "Not Available"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("download_attempts", models.IntegerField(default=0)),
                ("last_download_attempt", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("raw_api_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "lok_sabha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debates",
                        to="questions.loksabha",
                    ),
                ),
                (
                    "pdf_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debate",
                        to="files.documentfile",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debates",
                        to="questions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-debate_date"],
            },
        ),
        migrations.CreateModel(
            name="DebateSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_name", models.CharField(max_length=200)),
                ("speaker_designation", models.CharField(blank=True, max_length=200)),
                ("speech_text", models.TextField()),
                ("speech_order", models.IntegerField()),
                ("start_page", models.IntegerField(blank=True, null=True)),
                ("end_page", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="debates.debate",
                    ),
                ),
            ],
            options={
                "ordering": ["debate", "speech_order"],
            },
        ),
        migrations.CreateModel(
            name="DebateTagging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="debates.debate"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="debates.debatetag",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(
                fields=["lok_sabha", "session", "debate_date"],
                name="debates_deb_lok_sab_b70bc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(fields=["status"], name="debates_deb_status_c554b4_idx"),
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(
                fields=["debate_date"], name="debates_deb_debate__73a30e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="debate",
            unique_together={
                ("lok_sabha", "session", "debate_date", "debate_type", "language")
            },
        ),
        migrations.AddIndex(
            model_name="debatespeech",
            index=models.Index(
                fields=["debate", "speech_order"], name="debates_deb_debate__dd0e61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debatespeech",
            index=models.Index(
                fields=["speaker_name"], name="debates_deb_speaker_9a0c2b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="debatetagging",
            unique_together={("debate", "tag")},
        ),
    ]
