# Generated by Django 5.2.3 on 2025-09-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0001_initial"),
        ("questions", "0002_question_api_resource_id_question_assembly_no_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionDateCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("available_dates", models.JSONField(default=list)),
                ("session_period", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lok_sabha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_cache",
                        to="questions.loksabha",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_cache",
                        to="questions.session",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lok_sabha", "session"],
                        name="debates_ses_lok_sab_4b3a1d_idx",
                    ),
                    models.Index(
                        fields=["last_updated"], name="debates_ses_last_up_2f29c4_idx"
                    ),
                ],
                "unique_together": {("lok_sabha", "session")},
            },
        ),
    ]
