# Generated by Django 5.2.3 on 2025-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0002_sessiondatecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiondatecache",
            name="api_source",
            field=models.CharField(
                default="sansad.in",
                help_text="API source used to fetch this data",
                max_length=100,
            ),
        ),
    ]
