# Generated by Django 5.2.3 on 2025-09-26 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0003_sessiondatecache_api_source"),
        ("questions", "0005_alter_question_answer_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebateMasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lok_sabha_number", models.CharField(max_length=10)),
                ("session_number", models.CharField(max_length=10)),
                (
                    "available_dates",
                    models.JSONField(
                        default=list,
                        help_text="List of all available debate dates for this session",
                    ),
                ),
                (
                    "session_period",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Session period information from API",
                    ),
                ),
                (
                    "date_range_start",
                    models.DateField(
                        blank=True, help_text="First available debate date", null=True
                    ),
                ),
                (
                    "date_range_end",
                    models.DateField(
                        blank=True, help_text="Last available debate date", null=True
                    ),
                ),
                (
                    "total_debate_days",
                    models.IntegerField(
                        default=0, help_text="Total number of days with debates"
                    ),
                ),
                (
                    "debates_discovered",
                    models.IntegerField(
                        default=0,
                        help_text="Number of debates discovered for this session",
                    ),
                ),
                (
                    "debates_downloaded",
                    models.IntegerField(
                        default=0, help_text="Number of debates successfully downloaded"
                    ),
                ),
                (
                    "api_source",
                    models.CharField(
                        default="sansad.in",
                        help_text="Primary API source used to fetch this data",
                        max_length=100,
                    ),
                ),
                (
                    "fallback_api_sources",
                    models.JSONField(
                        default=list, help_text="List of fallback API sources used"
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether all available debates for this session have been discovered",
                    ),
                ),
                (
                    "last_discovery_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time we attempted to discover debates",
                        null=True,
                    ),
                ),
                (
                    "discovery_success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the last discovery attempt was successful",
                    ),
                ),
                (
                    "raw_api_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw response from the API"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_fetched", models.DateTimeField(auto_now=True)),
                (
                    "lok_sabha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_master_data",
                        to="questions.loksabha",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debate_master_data",
                        to="questions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-lok_sabha_number", "-session_number"],
                "indexes": [
                    models.Index(
                        fields=["lok_sabha_number", "session_number"],
                        name="debates_deb_lok_sab_0036a9_idx",
                    ),
                    models.Index(
                        fields=["lok_sabha", "session"],
                        name="debates_deb_lok_sab_18db6a_idx",
                    ),
                    models.Index(
                        fields=["is_complete"], name="debates_deb_is_comp_98a7c4_idx"
                    ),
                    models.Index(
                        fields=["last_fetched"], name="debates_deb_last_fe_fcb797_idx"
                    ),
                ],
                "unique_together": {("lok_sabha_number", "session_number")},
            },
        ),
    ]
