# Generated by Django 5.2.3 on 2025-09-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0004_add_debate_master_data"),
        ("files", "0003_add_gcs_fields"),
        ("questions", "0006_add_parliament_institution_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="debate",
            name="debates_deb_lok_sab_b70bc2_idx",
        ),
        migrations.RemoveIndex(
            model_name="debatemasterdata",
            name="debates_deb_lok_sab_0036a9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="debate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="debatemasterdata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="debate",
            name="debate_category",
            field=models.CharField(
                choices=[
                    ("uncorrected", "Uncorrected Proceedings"),
                    ("corrected", "Corrected Proceedings"),
                    ("synopsis", "Synopsis"),
                    ("text_of_debate", "Text of Debate"),
                ],
                default="uncorrected",
                help_text="Whether this is corrected or uncorrected proceedings",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="debate",
            name="parent_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debates",
                to="questions.parliamentinstitution",
            ),
        ),
        migrations.AddField(
            model_name="debatemasterdata",
            name="parent_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debate_master_data",
                to="questions.parliamentinstitution",
            ),
        ),
        migrations.AddField(
            model_name="debatemasterdata",
            name="rajya_sabha_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="debate",
            unique_together={
                (
                    "parent_institution",
                    "lok_sabha",
                    "session",
                    "debate_date",
                    "debate_category",
                    "language",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="debatemasterdata",
            unique_together={
                ("parent_institution", "lok_sabha_number", "session_number")
            },
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(
                fields=["parent_institution", "lok_sabha", "session", "debate_date"],
                name="debates_deb_parent__7160b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="debate",
            index=models.Index(
                fields=["debate_category"], name="debates_deb_debate__712165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="debatemasterdata",
            index=models.Index(
                fields=["parent_institution", "lok_sabha_number", "session_number"],
                name="debates_deb_parent__b5e735_idx",
            ),
        ),
    ]
