# Generated by Django 5.2.3 on 2025-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0007_add_rs_debate_support'),
        ('files', '0004_alter_documentfile_document_category_and_more'),
        ('questions', '0009_questionmasterdata_metadata_hash'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debate',
            name='debates_deb_parent__7160b5_idx',
        ),
        migrations.RenameIndex(
            model_name='debate',
            new_name='debates_deb_time_sl_bb7551_idx',
            old_name='debates_deb_time_sl_idx',
        ),
        migrations.AddField(
            model_name='debate',
            name='metadata_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash of metadata for duplicate detection', max_length=64),
        ),
        migrations.AddField(
            model_name='debatemasterdata',
            name='metadata_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash of metadata for duplicate detection', max_length=64),
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['parent_institution', 'debate_date'], name='debates_deb_parent__31a5cc_idx'),
        ),
    ]
