# Generated by Django 5.2.3 on 2025-10-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0008_remove_debate_debates_deb_parent__7160b5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatemasterdata',
            name='debate_category',
            field=models.CharField(default='corrected', help_text='Debate category: corrected, uncorrected, verbatim, official', max_length=50),
        ),
    ]
