# Generated by Django 5.2.3 on 2025-10-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0009_debatemasterdata_debate_category'),
        ('questions', '0009_questionmasterdata_metadata_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debatemasterdata',
            unique_together={('parent_institution', 'lok_sabha_number', 'session_number', 'debate_category')},
        ),
    ]
