# Generated by Django 5.2.3 on 2025-10-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0011_optimize_for_sequential_processing'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debate',
            name='idx_debate_status_date',
        ),
        migrations.RemoveIndex(
            model_name='debate',
            name='idx_debate_inst_status_date',
        ),
        migrations.RemoveIndex(
            model_name='debate',
            name='idx_debate_session_sequential',
        ),
    ]
