# Generated by Django 5.2.3 on 2025-06-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("pages_visited", models.IntegerField(default=0)),
                ("api_calls_made", models.IntegerField(default=0)),
                ("files_downloaded", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("api_call", "API Call"),
                            ("download", "File Download"),
                            ("search", "Search Query"),
                            ("profile_update", "Profile Update"),
                            ("subscription_change", "Subscription Change"),
                            ("export", "Data Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_auth.usersession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("key_prefix", models.CharField(max_length=10)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read Access"),
                            ("download", "Download Access"),
                            ("full", "Full Access"),
                            ("admin", "Admin Access"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                ("allowed_ips", models.TextField(blank=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="user_auth_a_key_5f4cb8_idx"),
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_auth_a_user_id_c533c7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("scraping", "Scraping Update"),
                            ("download", "Download Complete"),
                            ("subscription", "Subscription Alert"),
                            ("api_limit", "API Limit Warning"),
                            ("security", "Security Alert"),
                            ("feature", "New Feature"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("action_url", models.URLField(blank=True)),
                ("action_text", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="user_auth_u_user_id_4f59ab_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="user_auth_u_notific_5fe1f0_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("researcher", "Researcher"),
                            ("journalist", "Journalist"),
                            ("government", "Government Official"),
                            ("student", "Student"),
                            ("citizen", "Citizen"),
                            ("ngo", "NGO/Civil Society"),
                            ("academic", "Academic Institution"),
                            ("other", "Other"),
                        ],
                        default="citizen",
                        max_length=20,
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("basic", "Basic Plan"),
                            ("pro", "Professional Plan"),
                            ("enterprise", "Enterprise Plan"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("subscription_start", models.DateTimeField(blank=True, null=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("daily_api_limit", models.IntegerField(default=100)),
                ("monthly_download_limit", models.IntegerField(default=50)),
                ("api_calls_today", models.IntegerField(default=0)),
                ("downloads_this_month", models.IntegerField(default=0)),
                ("last_api_call", models.DateTimeField(blank=True, null=True)),
                ("last_download", models.DateTimeField(blank=True, null=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("newsletter_subscription", models.BooleanField(default=False)),
                ("data_export_format", models.CharField(default="json", max_length=10)),
                ("is_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_type"], name="user_auth_u_user_ty_e668ab_idx"
                    ),
                    models.Index(
                        fields=["subscription_tier"],
                        name="user_auth_u_subscri_e7473e_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="user_auth_u_is_veri_356c98_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="user_auth_u_user_id_95cbbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="user_auth_u_session_b9e700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["ip_address"], name="user_auth_u_ip_addr_26e9de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "activity_type"], name="user_auth_u_user_id_256ad1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["timestamp"], name="user_auth_u_timesta_828a41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["endpoint"], name="user_auth_u_endpoin_c0fd2a_idx"
            ),
        ),
    ]
