# Generated by Django 5.2.3 on 2025-06-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("api", "API Endpoint"),
                            ("file", "File Upload"),
                            ("manual", "Manual Entry"),
                            ("external", "External Source"),
                        ],
                        default="api",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("auth_required", models.BooleanField(default=False)),
                ("auth_type", models.CharField(blank=True, max_length=50)),
                ("rate_limit", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "api_base_url",
                    models.URLField(default="https://eparlib.sansad.in/restv3"),
                ),
                ("api_timeout", models.IntegerField(default=30)),
                ("max_retries", models.IntegerField(default=3)),
                ("delay_between_requests", models.FloatField(default=0.5)),
                ("default_batch_size", models.IntegerField(default=100)),
                ("default_workers", models.IntegerField(default=5)),
                ("enable_parallel_processing", models.BooleanField(default=True)),
                ("update_existing_questions", models.BooleanField(default=True)),
                ("create_missing_members", models.BooleanField(default=True)),
                ("create_missing_ministries", models.BooleanField(default=True)),
                ("auto_scrape_enabled", models.BooleanField(default=False)),
                ("auto_scrape_frequency", models.IntegerField(default=24)),
                ("last_auto_scrape", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_scrape", "Full Scrape"),
                            ("incremental", "Incremental Update"),
                            ("specific_session", "Specific Session"),
                            ("retry_failed", "Retry Failed"),
                        ],
                        default="incremental",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_questions_expected", models.IntegerField(default=0)),
                ("questions_processed", models.IntegerField(default=0)),
                ("questions_created", models.IntegerField(default=0)),
                ("questions_updated", models.IntegerField(default=0)),
                ("questions_failed", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=100)),
                ("worker_count", models.IntegerField(default=5)),
                ("max_retries", models.IntegerField(default=3)),
                ("delay_between_requests", models.FloatField(default=0.5)),
                ("worker_id", models.CharField(blank=True, max_length=50)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_lok_sabhas",
                    models.ManyToManyField(blank=True, to="questions.loksabha"),
                ),
                (
                    "target_sessions",
                    models.ManyToManyField(blank=True, to="questions.session"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partially_completed", "Partially Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("processed_questions", models.IntegerField(default=0)),
                ("successful_questions", models.IntegerField(default=0)),
                ("failed_questions", models.IntegerField(default=0)),
                ("current_start_position", models.IntegerField(default=0)),
                ("batch_size", models.IntegerField(default=100)),
                ("last_question_id", models.CharField(blank=True, max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "lok_sabha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.loksabha",
                    ),
                ),
                (
                    "scraping_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="scraper.scrapingjob",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("api_error", "API Error"),
                            ("parsing_error", "Data Parsing Error"),
                            ("database_error", "Database Error"),
                            ("network_error", "Network Error"),
                            ("timeout_error", "Timeout Error"),
                            ("rate_limit", "Rate Limit Exceeded"),
                            ("unknown", "Unknown Error"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True)),
                ("api_endpoint", models.URLField(blank=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("question_id", models.CharField(blank=True, max_length=50)),
                ("is_resolved", models.BooleanField(default=False)),
                ("retry_count", models.IntegerField(default=0)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scraping_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="scraper.scrapingjob",
                    ),
                ),
                (
                    "scraping_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraper.scrapingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="scrapingjob",
            index=models.Index(fields=["status"], name="scraper_scr_status_9d7778_idx"),
        ),
        migrations.AddIndex(
            model_name="scrapingjob",
            index=models.Index(
                fields=["job_type", "status"], name="scraper_scr_job_typ_3fe712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingjob",
            index=models.Index(
                fields=["started_at"], name="scraper_scr_started_23a2cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scrapingsession",
            unique_together={("scraping_job", "lok_sabha", "session")},
        ),
        migrations.AddIndex(
            model_name="scrapingerror",
            index=models.Index(
                fields=["scraping_job", "error_type"],
                name="scraper_scr_scrapin_6ea205_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingerror",
            index=models.Index(
                fields=["occurred_at"], name="scraper_scr_occurre_541838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingerror",
            index=models.Index(
                fields=["is_resolved"], name="scraper_scr_is_reso_5c5505_idx"
            ),
        ),
    ]
