# Generated by Django 5.2.3 on 2025-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scrapingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_scrape", "Full Scrape"),
                    ("incremental", "Incremental Update"),
                    ("specific_session", "Specific Session"),
                    ("retry_failed", "Retry Failed"),
                    ("debates", "Debate Scraping"),
                ],
                default="incremental",
                max_length=20,
            ),
        ),
    ]
