# Generated by Django 5.2.3 on 2025-09-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_scrapingjob_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapingjob",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for tracking",
                max_length=255,
                null=True,
            ),
        ),
    ]
