# Generated by Django 5.2.3 on 2025-06-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("summary", "Document Summary"),
                            ("metadata_extraction", "Metadata Extraction"),
                            ("topic_classification", "Topic Classification"),
                            ("sentiment_analysis", "Sentiment Analysis"),
                            ("entity_extraction", "Entity Extraction"),
                            ("full_analysis", "Full Analysis"),
                        ],
                        default="summary",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_model", models.CharField(default="gpt-3.5-turbo", max_length=100)),
                ("batch_size", models.IntegerField(default=10)),
                ("max_tokens", models.IntegerField(default=1000)),
                ("temperature", models.FloatField(default=0.3)),
                ("total_questions", models.IntegerField(default=0)),
                ("processed_questions", models.IntegerField(default=0)),
                ("successful_analyses", models.IntegerField(default=0)),
                ("failed_analyses", models.IntegerField(default=0)),
                ("total_tokens_used", models.BigIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, related_name="ai_jobs", to="questions.question"
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModelUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("provider", models.CharField(default="openai", max_length=50)),
                ("operation_type", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_per_input_token",
                    models.DecimalField(decimal_places=8, default=0, max_digits=10),
                ),
                (
                    "cost_per_output_token",
                    models.DecimalField(decimal_places=8, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("response_time", models.FloatField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_service.aianalysisjob",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary Generation"),
                            ("classification", "Topic Classification"),
                            ("extraction", "Entity Extraction"),
                            ("analysis", "General Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prompt_template", models.TextField()),
                ("system_message", models.TextField(blank=True)),
                ("variables", models.JSONField(blank=True, default=list)),
                ("recommended_model", models.CharField(blank=True, max_length=100)),
                ("max_tokens", models.IntegerField(default=1000)),
                ("temperature", models.FloatField(default=0.3)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_service.aiprompttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("brief", "Brief Summary"),
                            ("detailed", "Detailed Summary"),
                            ("executive", "Executive Summary"),
                            ("technical", "Technical Summary"),
                        ],
                        default="brief",
                        max_length=20,
                    ),
                ),
                ("summary_text", models.TextField()),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("word_count", models.IntegerField(default=0)),
                ("ai_model", models.CharField(default="gpt-3.5-turbo", max_length=100)),
                ("prompt_used", models.TextField(blank=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("processing_time", models.FloatField(default=0)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("human_reviewed", models.BooleanField(default=False)),
                ("human_rating", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_service.aianalysisjob",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MetadataExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("people", models.JSONField(blank=True, default=list)),
                ("organizations", models.JSONField(blank=True, default=list)),
                ("locations", models.JSONField(blank=True, default=list)),
                ("dates_mentioned", models.JSONField(blank=True, default=list)),
                ("amounts", models.JSONField(blank=True, default=list)),
                ("primary_topics", models.JSONField(blank=True, default=list)),
                ("secondary_topics", models.JSONField(blank=True, default=list)),
                ("policy_areas", models.JSONField(blank=True, default=list)),
                ("urgency_level", models.CharField(blank=True, max_length=20)),
                ("sentiment", models.CharField(blank=True, max_length=20)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("complexity_score", models.FloatField(blank=True, null=True)),
                ("readability_score", models.FloatField(blank=True, null=True)),
                ("question_intent", models.CharField(blank=True, max_length=50)),
                ("requires_action", models.BooleanField(blank=True, null=True)),
                ("follow_up_needed", models.BooleanField(blank=True, null=True)),
                ("ai_model", models.CharField(default="gpt-3.5-turbo", max_length=100)),
                ("confidence_scores", models.JSONField(blank=True, default=dict)),
                ("processing_notes", models.TextField(blank=True)),
                ("human_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_service.aianalysisjob",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_metadata",
                        to="questions.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_name", models.CharField(max_length=200)),
                ("topic_category", models.CharField(blank=True, max_length=100)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "classification_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic Classification"),
                            ("manual", "Manual Classification"),
                            ("hybrid", "Human-AI Hybrid"),
                        ],
                        default="automatic",
                        max_length=20,
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("keywords_matched", models.JSONField(blank=True, default=list)),
                ("ai_reasoning", models.TextField(blank=True)),
                ("human_validated", models.BooleanField(default=False)),
                ("validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_service.aianalysisjob",
                    ),
                ),
                (
                    "parent_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_service.topicclassification",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_classifications",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.AddIndex(
            model_name="aianalysisjob",
            index=models.Index(fields=["status"], name="ai_service__status_73fe15_idx"),
        ),
        migrations.AddIndex(
            model_name="aianalysisjob",
            index=models.Index(
                fields=["job_type", "status"], name="ai_service__job_typ_533eac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelusage",
            index=models.Index(
                fields=["model_name", "used_at"], name="ai_service__model_n_419177_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelusage",
            index=models.Index(
                fields=["operation_type"], name="ai_service__operati_b873ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelusage",
            index=models.Index(
                fields=["success"], name="ai_service__success_a6255c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(
                fields=["template_type", "is_active"],
                name="ai_service__templat_31381c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(
                fields=["is_default"], name="ai_service__is_defa_168888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentsummary",
            index=models.Index(
                fields=["question", "summary_type"],
                name="ai_service__questio_846460_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsummary",
            index=models.Index(
                fields=["human_reviewed"], name="ai_service__human_r_ed29cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentsummary",
            unique_together={("question", "summary_type")},
        ),
        migrations.AddIndex(
            model_name="metadataextraction",
            index=models.Index(
                fields=["urgency_level"], name="ai_service__urgency_9113d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadataextraction",
            index=models.Index(
                fields=["sentiment"], name="ai_service__sentime_e1d47c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadataextraction",
            index=models.Index(
                fields=["human_verified"], name="ai_service__human_v_0daa06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicclassification",
            index=models.Index(
                fields=["topic_category"], name="ai_service__topic_c_8d4090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicclassification",
            index=models.Index(
                fields=["confidence_score"], name="ai_service__confide_993ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicclassification",
            index=models.Index(
                fields=["classification_type"], name="ai_service__classif_7c2850_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topicclassification",
            unique_together={("question", "topic_name")},
        ),
    ]
