# Generated by Django 5.2.3 on 2025-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="api_resource_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="assembly_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="committee_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="council_of_state_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="debate",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="document_handle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="document_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="minister_names",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="pdf_files",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="report_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="question",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="year",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="question",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
