# Generated by Django 5.2.3 on 2025-09-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_question_api_resource_id_question_assembly_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="dates",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="session",
            name="raw_api_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="session",
            name="session_period",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="QuestionMasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.CharField(max_length=50)),
                ("subjects", models.TextField()),
                ("lok_sabha_number", models.CharField(max_length=10)),
                ("members", models.JSONField(default=list)),
                ("ministry", models.CharField(max_length=200)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("STARRED", "Starred Question"),
                            ("UNSTARRED", "Unstarred Question"),
                            ("SHORT_NOTICE", "Short Notice Question"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("session_number", models.CharField(max_length=10)),
                ("questions_file_path", models.URLField(blank=True)),
                ("questions_file_path_hindi", models.URLField(blank=True)),
                ("question_text", models.TextField(blank=True)),
                ("answer_text", models.TextField(blank=True)),
                ("answer_text_hindi", models.TextField(blank=True)),
                ("supplementary_type", models.BooleanField(default=False)),
                ("supplementary_questions", models.JSONField(blank=True, default=list)),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_api_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_fetched", models.DateTimeField(auto_now=True)),
                (
                    "lok_sabha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_questions",
                        to="questions.loksabha",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_questions",
                        to="questions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-question_number"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="master_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question",
                to="questions.questionmasterdata",
            ),
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(
                fields=["lok_sabha_number", "session_number"],
                name="questions_q_lok_sab_186025_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(
                fields=["question_type"], name="questions_q_questio_404636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(
                fields=["is_processed"], name="questions_q_is_proc_ef48b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(fields=["date"], name="questions_q_date_9b6a74_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="questionmasterdata",
            unique_together={("question_number", "lok_sabha_number", "session_number")},
        ),
    ]
