# Generated by Django 5.2.3 on 2025-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_session_dates_session_raw_api_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionmasterdata",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionmasterdata",
            name="answer_text_hindi",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionmasterdata",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
