# Generated by Django 5.2.3 on 2025-09-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_alter_questionmasterdata_answer_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
