# Generated by Django 5.2.3 on 2025-09-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_question_answer_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParliamentInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("lok_sabha", "Lok Sabha"),
                            ("rajya_sabha", "Rajya Sabha"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="questionmasterdata",
            name="questions_q_lok_sab_186025_idx",
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="rajya_sabha_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="questionmasterdata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="question",
            name="parent_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="questions.parliamentinstitution",
            ),
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="parent_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_master_data",
                to="questions.parliamentinstitution",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionmasterdata",
            unique_together={
                (
                    "parent_institution",
                    "question_number",
                    "lok_sabha_number",
                    "session_number",
                )
            },
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(
                fields=["parent_institution", "lok_sabha_number", "session_number"],
                name="questions_q_parent__621ca7_idx",
            ),
        ),
    ]
