# Generated by Django 5.2.3 on 2025-09-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_add_parliament_institution_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionmasterdata",
            unique_together={
                (
                    "parent_institution",
                    "question_number",
                    "lok_sabha_number",
                    "session_number",
                    "question_type",
                )
            },
        ),
    ]
