# Generated by Django 5.2.3 on 2025-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0007_alter_questionmasterdata_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionmasterdata",
            name="pdf_download_attempted_at",
            field=models.DateTimeField(
                blank=True, help_text="Last PDF download attempt timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="pdf_download_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of PDF download attempts"
            ),
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="pdf_download_error",
            field=models.TextField(
                blank=True, help_text="Last PDF download error message"
            ),
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="pdf_downloaded",
            field=models.BooleanField(
                default=False, help_text="Whether PDF has been downloaded to GCS"
            ),
        ),
        migrations.AddField(
            model_name="questionmasterdata",
            name="pdf_gcs_path",
            field=models.CharField(
                blank=True, help_text="GCS path where PDF is stored", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="questionmasterdata",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="Whether metadata has been converted to Question record",
            ),
        ),
        migrations.AlterField(
            model_name="questionmasterdata",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When metadata was converted to Question record",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="questionmasterdata",
            index=models.Index(
                fields=["pdf_downloaded"], name="questions_q_pdf_dow_f9b265_idx"
            ),
        ),
    ]
