# Generated by Django 5.2.3 on 2025-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_add_pdf_download_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmasterdata',
            name='metadata_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash of metadata for duplicate detection', max_length=64),
        ),
    ]
