# Generated by Django 5.2.3 on 2025-06-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("question", "Question Document"),
                            ("answer", "Answer Document"),
                            ("combined", "Combined Q&A Document"),
                            ("appendix", "Appendix"),
                            ("other", "Other"),
                        ],
                        default="question",
                        max_length=20,
                    ),
                ),
                ("original_url", models.URLField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="pdfs/"),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Download Pending"),
                            ("downloading", "Currently Downloading"),
                            ("completed", "Download Completed"),
                            ("failed", "Download Failed"),
                            ("not_available", "Not Available"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("download_attempts", models.IntegerField(default=0)),
                ("last_download_attempt", models.DateTimeField(blank=True, null=True)),
                ("download_error", models.TextField(blank=True)),
                ("download_priority", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="questions.question",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partially_failed", "Partially Failed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("completed_files", models.IntegerField(default=0)),
                ("failed_files", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="download_batches", to="questions.question"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DownloadQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("worker_id", models.CharField(blank=True, max_length=50)),
                ("progress_percent", models.IntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_jobs",
                        to="files.documentfile",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("access_type", models.CharField(default="download", max_length=50)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="files.documentfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(fields=["status"], name="files_docum_status_cd785f_idx"),
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(
                fields=["question", "file_type"], name="files_docum_questio_bd64f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(
                fields=["download_priority", "created_at"],
                name="files_docum_downloa_a22d1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="downloadqueue",
            index=models.Index(
                fields=["status", "priority"], name="files_downl_status_a2b59e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadqueue",
            index=models.Index(
                fields=["created_at"], name="files_downl_created_54bb1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(
                fields=["document_file", "accessed_at"],
                name="files_filea_documen_28fb0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(
                fields=["user", "accessed_at"], name="files_filea_user_id_35d1b2_idx"
            ),
        ),
    ]
