# Generated by Django 5.2.3 on 2025-09-18 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("questions", "0002_question_api_resource_id_question_assembly_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="document_category",
            field=models.CharField(
                choices=[
                    ("parl_question", "Parliamentary Question"),
                    ("parl_debate", "Parliamentary Debate"),
                    ("parl_answer", "Parliamentary Answer"),
                    ("parl_appendix", "Parliamentary Appendix"),
                    ("parl_committee", "Committee Report"),
                    ("parl_bill", "Bill Document"),
                    ("other", "Other Document"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("question", "Question Document"),
                    ("answer", "Answer Document"),
                    ("combined", "Combined Q&A Document"),
                    ("debate", "Debate Transcript"),
                    ("appendix", "Appendix"),
                    ("committee_report", "Committee Report"),
                    ("bill", "Bill Document"),
                    ("other", "Other"),
                ],
                default="question",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="questions.question",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfile",
            index=models.Index(
                fields=["document_category", "file_type"],
                name="files_docum_documen_60836c_idx",
            ),
        ),
    ]
