# Generated by Django 5.2.3 on 2025-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_documentfile_document_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="gcs_bucket_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="gcs_etag",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="gcs_object_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="gcs_upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Upload Pending"),
                    ("uploading", "Currently Uploading"),
                    ("completed", "Upload Completed"),
                    ("failed", "Upload Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="gcs_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentfile",
            name="gcs_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
