# Generated by Django 5.2.3 on 2025-09-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_add_gcs_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentfile",
            name="document_category",
            field=models.CharField(
                choices=[
                    ("parl_question", "Parliamentary Question"),
                    ("parl_rs_question", "Rajya Sabha Question"),
                    ("parl_debate", "Parliamentary Debate"),
                    ("parl_answer", "Parliamentary Answer"),
                    ("parl_appendix", "Parliamentary Appendix"),
                    ("parl_committee", "Committee Report"),
                    ("parl_bill", "Bill Document"),
                    ("other", "Other Document"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("question", "Question Document"),
                    ("rs_question", "Rajya Sabha Question Document"),
                    ("answer", "Answer Document"),
                    ("combined", "Combined Q&A Document"),
                    ("debate", "Debate Transcript"),
                    ("appendix", "Appendix"),
                    ("committee_report", "Committee Report"),
                    ("bill", "Bill Document"),
                    ("other", "Other"),
                ],
                default="question",
                max_length=20,
            ),
        ),
    ]
