# Generated by Django 5.2.3 on 2025-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_increase_file_path_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='file_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='pdfs/'),
        ),
    ]
