"""
Django settings for parliament_api project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file  
# BASE_DIR is parliament_proceedings/parliament_api/, .env is in the same directory
env_path = BASE_DIR / '.env'
if not env_path.exists():
    raise FileNotFoundError(f".env file not found at: {env_path}")
# override=True ensures .env values override any existing environment variables
load_dotenv(env_path, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-@$nyjnxgv9l2qa)20+5e-i=4ti%il&qa=2x(h_pe1ntn*5tydx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "corsheaders",
    # Custom apps
    "services.scraper",
    "services.questions",
    "services.debates",
    "services.files",
    "services.ai_service",
    "services.user_auth",
    "services.cloud_storage",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "parliament_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "parliament_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME', 'parliament_api'),
        "USER": os.getenv('DB_USER', 'parliament_user'),
        "PASSWORD": os.getenv('DB_PASSWORD', '***REMOVED_SECRET***'),
        "HOST": os.getenv('DB_HOST', 'localhost'),
        "PORT": os.getenv('DB_PORT', '5432'),
        "CONN_MAX_AGE": int(os.getenv('DB_CONN_MAX_AGE', '600')),
        "CONN_HEALTH_CHECKS": os.getenv('DB_CONN_HEALTH_CHECKS', 'true').lower() == 'true',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Enable authentication for all endpoints
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Parliament Proceedings API',
    'DESCRIPTION': 'A comprehensive REST API for accessing parliamentary questions and answers data from the Indian Parliament',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development Server'},
        {'url': 'https://api.parliament.example.com', 'description': 'Production Server'},
    ],
    'TAGS': [
        {'name': 'Questions', 'description': 'Parliamentary questions and answers'},
        {'name': 'Debates', 'description': 'Parliamentary debates and proceedings'},
        {'name': 'Scraper', 'description': 'Data scraping and synchronization'},
        {'name': 'Files', 'description': 'PDF downloads and file management'},
        {'name': 'AI Service', 'description': 'AI analysis and summarization'},
        {'name': 'Authentication', 'description': 'User authentication and management'},
        {'name': 'Admin', 'description': 'Administrative operations'},
    ],
    'CONTACT': {
        'name': 'Parliament API Support',
        'email': 'support@parliamentapi.com',
    },
    'LICENSE': {
        'name': 'MIT License',
        'url': 'https://opensource.org/licenses/MIT',
    },
    'EXTERNAL_DOCS': {
        'description': 'Find more info here',
        'url': 'https://github.com/your-repo/parliament-api',
    },
}

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

# File Upload Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# API Request Rate Limiting
API_REQUEST_DELAY_MIN = float(os.getenv('API_REQUEST_DELAY_MIN', '0.1'))  # Minimum delay in seconds
API_REQUEST_DELAY_MAX = float(os.getenv('API_REQUEST_DELAY_MAX', '0.3'))  # Maximum delay in seconds

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = [os.getenv('CELERY_ACCEPT_CONTENT', 'json')]
CELERY_TASK_SERIALIZER = os.getenv('CELERY_TASK_SERIALIZER', 'json')
CELERY_RESULT_SERIALIZER = os.getenv('CELERY_RESULT_SERIALIZER', 'json')
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')

# Celery Worker Configuration
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '8'))
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.getenv('CELERY_WORKER_MAX_TASKS_PER_CHILD', '1000'))

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'parliament.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'services.scraper': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.questions': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.debates': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.files': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'services.ai_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Also add the short names for backward compatibility
        'scraper': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'questions': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'debates': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'files': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ai_service': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Root logger for Django
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Catch-all root logger
        '': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
        },
    },
}

# Parliament API Specific Settings
PARLIAMENT_API_BASE_URL = "https://eparlib.sansad.in/restv3"
PARLIAMENT_SANSAD_URL = "https://sansad.in/api_ls"
PARLIAMENT_SCRAPER_BATCH_SIZE = 100
PARLIAMENT_SCRAPER_WORKERS = 5
PARLIAMENT_TARGET_SESSIONS = ["15", "16", "17"]

# PDF Storage Settings
PDF_STORAGE_PATH = MEDIA_ROOT / 'pdfs'
PDF_DOWNLOAD_TIMEOUT = 30
PDF_MAX_PARALLEL_DOWNLOADS = 10

# AI Service Settings (placeholders for now)
AI_SERVICE_ENABLED = False
AI_API_KEY = ""  # To be set via environment variables
AI_MODEL_NAME = "gpt-3.5-turbo"  # Default model

# Google Cloud Storage Settings - ALL VALUES MUST BE IN .env
GCS_PROJECT_ID = os.environ['GCS_PROJECT_ID']  # Will crash if not in .env
GCS_CREDENTIALS_PATH = os.getenv('GCS_CREDENTIALS_PATH', BASE_DIR / 'parliament-process-90c920ce4243.json')
GCS_DEBATES_BUCKET = os.environ['GCS_DEBATES_BUCKET']  # Will crash if not in .env
GCS_QUESTIONS_BUCKET = os.environ['GCS_QUESTIONS_BUCKET']  # Will crash if not in .env
GCS_PRESIGNED_URL_EXPIRATION = int(os.environ.get('GCS_PRESIGNED_URL_EXPIRATION', '3600'))
GCS_AUTO_DELETE_LOCAL = os.environ.get('GCS_AUTO_DELETE_LOCAL', 'true').lower() == 'true'
GCS_REGION = os.environ.get('GCS_REGION', 'asia-south1')

# Admin User Settings (for initial setup)
ADMIN_USERNAME = os.getenv('ADMIN_USERNAME', 'parliament_admin')
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD', 'ParliamentAPI@2025#Secure')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'admin@parliament-api.gov.in')
